
package zombiedefense;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class VentanaJuego extends javax.swing.JFrame {
    //Etiquetas del tablero
    public static JLabel etiqueta1,etiqueta2,etiqueta3,etiqueta4,etiqueta5,etiqueta6,etiqueta7,etiqueta8,etiqueta9,etiqueta10,etiqueta11,etiqueta12,
            etiqueta13,etiqueta14,etiqueta15,etiqueta16,etiqueta17,etiqueta18,etiqueta19,etiqueta20,etiqueta21,etiqueta22,etiqueta23,etiqueta24,
            etiqueta25,etiqueta26,etiqueta27,etiqueta28,etiqueta29,etiqueta30;
    
    //Variables que se utilizan para representar el juego
    public static JLabel[] arregloEtiquetas = new JLabel[35];
    public static JLabel[][] matrizEtiquetas = new JLabel[7][5];//Matriz Grafica
    public static Personaje[][] matrizObjetos = new Personaje[7][5];//Matriz Logica
    public static int turnos;
        
    public VentanaJuego() {
        initComponents();
        this.setLocationRelativeTo(null);
        IniciarTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        tablero = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelMensaje1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tablero.setVisible(true);

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero.getContentPane());
        tablero.getContentPane().setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1074, Short.MAX_VALUE)
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jButton2.setText("jButton2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 548, 140, 53));

        jLabelMensaje1.setText("Acciones del Jugador");
        jPanel1.add(jLabelMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablero))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tablero)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    //Metodos
    public void ActualizarMatriz(){
        for(int i = 0; i<7;i++){
            for(int j = 0;j<5;j++){
                if(matrizObjetos[i][j] instanceof Casilla){
                    Casilla elemento = (Casilla) matrizObjetos[i][j];
                    if(elemento.isObstaculizado()){
                        matrizEtiquetas[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Obstaculo.jpg")));
                    }
                    
                }
                else if(matrizObjetos[i][j] instanceof Asesino){
                   matrizEtiquetas[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CasillaAsesino.jpg")));
                   
                }
                else if(matrizObjetos[i][j] instanceof Blindado){
                    matrizEtiquetas[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CasillaPesado.jpg")));
                }
                else if(matrizObjetos[i][j] instanceof Chubby){
                   matrizEtiquetas[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChubbyCasilla.jpg")));
                }
                else if(matrizObjetos[i][j] instanceof Explorador){
                   matrizEtiquetas[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CasillaSniper.jpg")));
                }
                else if(matrizObjetos[i][j] instanceof Ghoul){
                    matrizEtiquetas[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GhoulCasilla.jpg")));
                }
                else {
                    matrizEtiquetas[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LakelurkCasilla.jpg")));
                }
                
            }
        }
         
        
    } 
    
    
    public void IniciarTablero(){
        tablero.setLayout(new GridLayout(7,5,5,5));//LLenar el arreglo de todos los labels
        for(int i = 0; i<arregloEtiquetas.length;i++){
            arregloEtiquetas[i] = new JLabel();
            arregloEtiquetas[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CasillaDefault.jpg")));
            tablero.add(arregloEtiquetas[i]);
        }
        //Llenar la matriz de etiquetas
        int e = 0;
        while(e<35){
            for(int x = 0;x<7;x++){
                for(int y = 0;y<5;y++){
                    matrizEtiquetas[x][y] = arregloEtiquetas[e];
                    e++;
                }
            }
        }
        //Inicializar la matriz de objetos poniendo todo en casillas
        for(int i = 0; i<7;i++){
            for(int j = 0;j<5;j++){
                matrizObjetos[i][j] = new Casilla(false, false, false, 0, 0, 0, 0, 0, 0);
            }
        }
        //Declaramos cual va a ser la entrada a la base
         for(int z = 0;z<5;z++){
            matrizObjetos[0][z] = new Casilla(false, false, true, 0, 0, 0, 0, 0, 0);
            matrizEtiquetas[0][z].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Entrada.jpg"))); 
        }
        //Pruebas
        matrizObjetos[3][3] = new Casilla(true, false, false, 0, 0, 0, 0, 0, 0);
        matrizObjetos[2][2] = new Asesino(0,0,0,0,0,0);
        matrizObjetos[1][1] = new Blindado(0, true,0,0,0,0,0,0);
        matrizObjetos[5][2] = new Chubby(0,0,0,0,0,0,0);
        matrizObjetos[1][4] = new Explorador(0,0,0,0,0,0);
        matrizObjetos[3][0] = new Ghoul(0,0,0,0,0,0,0);       
        matrizObjetos[4][0] = new Lakelurk(0,0,0,0,0,0,0);
        //Llamada a Actualizar
        ActualizarMatriz();
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMensaje1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JInternalFrame tablero;
    // End of variables declaration//GEN-END:variables
}
