/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zombiedefense;

/**
 *
 * @author DELL
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelZombi = new javax.swing.JLabel();
        jLabelHeroe = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelIngreseN = new javax.swing.JLabel();
        jLabelJugar = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelZombi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cooltext366225730489652.png"))); // NOI18N
        jLabelZombi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelZombiMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelZombi, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, -1, -1));

        jLabelHeroe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cooltext366225860297411.png"))); // NOI18N
        jLabelHeroe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHeroeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, -1, -1));

        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        jTextFieldNombre.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNombre.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(102, 0, 0));
        jTextFieldNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 490, 40));

        jLabelIngreseN.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabelIngreseN.setForeground(new java.awt.Color(102, 0, 0));
        jLabelIngreseN.setText("Ingrese un nombre para el personaje:");
        getContentPane().add(jLabelIngreseN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jLabelJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cool Text - Jugar 366228694806627.png"))); // NOI18N
        jLabelJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJugarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 1170, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void jLabelHeroeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHeroeMouseClicked
        PreviewHeroes cambio= new PreviewHeroes();
        cambio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelHeroeMouseClicked

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jLabelZombiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelZombiMouseClicked
        PreviewZombi cambioZ= new PreviewZombi();
        cambioZ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelZombiMouseClicked

    private void jLabelJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJugarMouseClicked
        String nombreIngresado= jTextFieldNombre.getText();
    if (nombreIngresado.equals("")){
        jTextFieldNombre.setText("Debe de ingresar un nombre.");
    }
    else{
    VentanaJuego cambioJ= new VentanaJuego();
    cambioJ.setVisible(true);
    this.dispose();
    }
    }//GEN-LAST:event_jLabelJugarMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelHeroe;
    private javax.swing.JLabel jLabelIngreseN;
    private javax.swing.JLabel jLabelJugar;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelZombi;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
